FROM python:3.8-slim
#for nextflow trace
RUN apt-get update && apt-get install -y --no-install-recommends procps && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN pip install fire numpy scikit-image aicsimageio pandas imagecodecs --no-cache-dir
COPY scripts/helper.py /usr/bin/helper
RUN chmod +x /usr/bin/helper
