FROM nvidia/cuda:11.2.0-cudnn8-runtime-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get -y update && apt-get -y install --no-install-recommends procps python3 python3-dev python3-pip python-is-python3 libgomp1 ffmpeg libsm6 libxext6 git wget

RUN pip install numpy==1.20 scipy tifffile fire \
     dask-image "dask[distributed]" imagecodecs \
     cellpose==1.0.2 cucim scipy scikit-image cupy-cuda112 ome-zarr==0.4.1 trackpy shapely \
     opencv-contrib-python-headless git+https://github.com/facebookresearch/segment-anything.git --no-cache-dir

RUN mkdir /opt/.cellpose && \
    chmod -R a+rw /opt/.cellpose && \
    ln -s /opt/.cellpose $HOME/.cellpose &&\
    python -c "from cellpose import models;models.Cellpose(gpu=True, model_type='cyto2')"
RUN wget https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth -P /sam/model/
RUn pip install onnxruntime onnx torchvision>=0.8
